### ISSUE TITLE
 http://www.cs.ubc.ca/research/flann/uploads/FLANN/datasets is down

### ISSUE THREAD

**Issue by paperchalice** [flann-lib/flann#477]
people.cs.ubc.ca/~mariusm/flann is down. All datasets are unreachable.

**Comment by melhashash** [comment]
Have you tried this PR [463](https://github.com/flann-lib/flann/pull/463)?

**Comment by paperchalice** [comment]
> Have you tried this PR [463](https://github.com/flann-lib/flann/pull/463)?

Error 500

**Comment by melhashash** [comment]
How about?

wget http://www.cs.ubc.ca/research/flann/uploads/FLANN/datasets/dataset.hdf5

**Comment by paperchalice** [comment]
Error 500, all url list [here](https://github.com/Homebrew/homebrew-core/blob/fd2e45832c59f35a4f781cc3356d98faa5c73b18/Formula/flann.rb#L28) are unavailable.

**Comment by melhashash** [comment]
I have uploaded them here [dataset.zip](https://github.com/flann-lib/flann/files/6518483/dataset.zip)

**Comment by monajalal** [comment]
@melhashash  could you please provide the link for downloading flann 1.9.1 source code?

**Comment by melhashash** [comment]
> @melhashash  could you please provide the link for downloading flann 1.9.1 source code?

Try [this](https://github.com/mariusmuja/flann/archive/1.9.1.tar.gz)
